---
- name: create folders for virtualenv
  raw: mkdir -p ~/{bin,tmp,lib/python2.7}

- name: install pip
  easy_install: executable=easy_install-2.7 name=pip

- name: install virtualenv
  raw: ~/bin/pip2.7 install virtualenv --no-use-wheel

- name: install virtualenvwrapper
  raw: ~/bin/pip2.7 install --install-option="--user" virtualenvwrapper --no-use-wheel

- name: add virtualenvwrapper exports to .bash_profile
  lineinfile: 'dest=~/.bash_profile line="{{ item }}"'
  with_items:
    - export PATH=$PATH:$HOME/bin
    - export TMPDIR=$HOME/tmp
    - export WORKON_HOME=$HOME/Envs
    - export VIRTUALENVWRAPPER_PYTHON=/usr/local/bin/python2.7
    - export PIP_VIRTUALENV_BASE=$WORKON_HOME
    - export PIP_RESPECT_VIRTUALENV=true
    - source $HOME/bin/virtualenvwrapper.sh

- name: source the new .bash_profile
  raw: source .bashrc
