---
- name: uWSGI create necessary folders
  shell: mkdir -p ~/logs/user/uwsgi

- name: Install uwsgi
  shell: ~/bin/pip2.7 install uwsgi

- name: Upload uwsgi.ini
  template: src=uwsgi.ini dest=~/local/etc/uwsgi.ini
