---
- name: Install zsh, vim, virtualenv, supervisor, gunicorn & a Django project on Webfaction
  hosts: webfaction-server
  vars_files:
    - vars/external_vars.yml
  user: "{{ username }}"

  roles:
    - virtualenv
    - common-python
    - nginx
    - uwsgi
    - nodejs
    - statsd
# TODO: first simple deployment here: - django
# TODO: install carbon & whisper next
    - whisper
    - supervisor
    - graphite-venv
# TODO: create django auth proxy before graphite-api
# https://github.com/DandyDev/graphite-statsd-ansible-vagrant/blob/master/roles/graphite/tasks/main.yml
