---
- name: Install zsh, vim, virtualenv, supervisor, gunicorn & a Django project on Webfaction
  hosts: webfaction-server
  vars_files:
    - vars/external_vars.yml
  user: "{{ username }}"

  roles:
    - virtualenv
    - common-python
    - django
    - nginx
    - uwsgi
    - nodejs
    - statsd
    - graphite-venv
    - carbon
    # TODO: install graphite-api: http://graphite-api.readthedocs.org/en/latest/installation.html
    #TODO: update supervisor for all parts of the stack
    # TODO: create django auth proxy before graphite-api

# Inspiration taken from:
# https://github.com/DandyDev/graphite-statsd-ansible-vagrant/blob/master/roles/graphite/tasks/main.yml
