---
- name: create folders for whisper
  shell: mkdir -p ~/src ~/opt/graphite ~/opt/graphite/whisper

- name: test if whisper has been cloned
  stat: /home/{{ username }}/src/whisper
  register: whisper_repo

- name: clone statsd from github
  git: repo=https://github.com/graphite-project/whisper/ dest=~/src/whisper update=no
  when: not whisper_repo.stat.exists

- name: pull latest whisper sources
  shell: git pull
  when: whisper_repo.stat.exists
  args:
    chdir: /home/{{ username }}/src/whisper

# TODO: Need to setup a virtualenv before installing whisper

- name: install whisper
  command: ./bin/pip install ./whisper-{{ graphite_version }}/ chdir=/opt/graphite
