---
- name: install common global python packages
  shell: ~/bin/pip2.7 install --install-option="--user" --no-use-wheel {{ item.name }}
  with_items:
    - { name: mercurial }
    - { name: ipython }
    - { name: psycopg2 }
    - { name: python-memcached }
